services:
  cli:
    build: .
    image: omnia-cli
    env_file:
      - .env
    volumes:
      - ${HOME}/.omnia:/root/.omnia
      - ./omnia:/app/omnia
    network_mode: host
    stdin_open: true
    tty: true
